# Generated by Django 4.0.6 on 2022-07-07 21:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
            ],
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('contacto', models.CharField(max_length=200, verbose_name='Contacto')),
                ('num_tel', models.CharField(max_length=40, null=True, verbose_name='Número de Teléfono')),
                ('correo', models.CharField(max_length=70, null=True, verbose_name='Correo Electronico')),
                ('nombre_comercial', models.CharField(max_length=200, verbose_name='Nombre Comercial')),
                ('giro', models.CharField(max_length=200, verbose_name='Giro')),
                ('localidad', models.CharField(max_length=100, verbose_name='Localidad')),
                ('fechaReg', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de Registro')),
                ('clasificacion', models.CharField(choices=[('A', 'Muy importante'), ('B', 'Importante'), ('C', 'Regular importancia '), ('D', 'Si compra bien, pero que no quite tiempo')], default='1', max_length=1)),
                ('fase', models.CharField(choices=[('F1', 'Buscar Nuevas Oportunidades de Negocio'), ('F2', 'Identificar Necesidades del Prospecto'), ('F3', 'Formular la Propuesta'), ('F4', 'Negociar el Cierre'), ('F5', 'Administrar la Implementación'), ('F6', 'Lista Negra')], default='1', max_length=2)),
                ('observaciones', models.CharField(max_length=254, null=True, verbose_name='Observaciones')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.responsable')),
            ],
        ),
    ]
