# Generated by Django 4.0.6 on 2022-07-07 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecto',
            name='fechaReg',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='Fecha de Registro'),
        ),
    ]
