# Generated by Django 4.0.6 on 2022-07-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_prospecto_coordenadas_alter_prospecto_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecto',
            name='clasificacion',
            field=models.CharField(choices=[('A', 'Prioridad Alta'), ('B', 'Muy Importante'), ('C', 'Importante'), ('D', 'Regular')], default='1', max_length=1),
        ),
    ]
